### ISSUE TITLE
Usage of requirements.yml in place of submodules

### ISSUE THREAD

**Issue by nqb** [lefilament/ansible#2]
Hello,

I suggest to use a `requirements.yml` + an `ansible.cfg` at root of repository to avoid usage of git submodules in this repository.

Example:

requirements.yml:
```yaml
roles:
  - name: docker_server
    src: https://github.com/lefilament/ansible_role_docker_server
    version: master
```

ansible.cfg:
```ini
# Installs **and** lookup collections into [current dir]/ansible_collections/namespace/collection_name
collections_paths = ./

# Installs **and** lookup roles into [current dir]/roles/namespace.rolename
roles_path = ./roles
```

Are you in favor of such change or do you prefer to keep things as-is ? If yes, I will open a PR.

NOTES: 
- it seems necessary to have a `meta/main.yml` in each role repository
- another solution is to move all roles inside this repository
